#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool hum = false;
	 //vexRT[Btn6U]=
	 //vexRT[Btn6D]=

	while (1)
	{

		if (vexRT[Btn6U] == 1 )
		{
			motor[arm]=127;
   		hum = true;
 		}
 		else
 		{
 			motor[arm]=0;
		}
		if (vexRT[Btn6D] == 1 )
		{
			hum = true;
			motor[arm]=-127;
		}
		else
		{
			motor[arm]=0;
		}
	}
}
