#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           arm,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool hum = false;
	 //vexRT[Btn6U]=
	 //vexRT[Btn6D]=
	if (vexRT[Btn5U] == 1 )
	{
		motor[port3]=127;
   hum = true;
 } else {
 	motor[port3]=0;
}
	if (vexRT[Btn5D] == 1 )
	{
		hum = true;
		motor[port6]=127;
	}	else {
	motor[port6]=0;
}
}
