#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void StandardDrive()
{
	motor[RightMotor] = vexRT(Ch2);
	motor[LeftMotor] = vexRT(Ch3);
}

void ArcadeDrive1Stick()
{
	motor[LeftMotor] = (vexRT[Ch2] + vexRT[Ch1])/2; // (y + x)/2
	motor[RightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2; // (y - x)/2
}

void ArcadeDrive2Stick()
{
	motor[LeftMotor] = (vexRT[Ch3] + vexRT[Ch1])/2; // (y + x)/2
	motor[RightMotor] = (vexRT[Ch3] - vexRT[Ch1])/2; // (y - x)/2
}

task main()
{
	while(1)
	{
		if(SensorValue[pot] < 2047)
		{
			ArcadeDrive2Stick();
		}
		else
		{
			ArcadeDrive1Stick();
		}
	}
}
